### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by Kubitomakita** [iflylabs/iflychat-app-translation#16]
I'm creating this issue because I couldn't push any branch to this repo and create a PR.

Please find the updated translation here: http://pastebin.com/jWkBrdjT

**Comment by shubh22** [comment]
We have merged the file to Repo. The updated translation is now live, thank you for your contribution.

**Comment by Kubitomakita** [comment]
Hi,

Please can you update it again. I found few misspels :)

Here is the most recent version: http://pastebin.com/CBBAHqPw

Thanks.

**Comment by darklrd** [comment]
Could you please open a separate pull request for the same? Thanks.
